services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rumbler-portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    networks:
      - portfolio-net

networks:
  portfolio-net:
    name: portfolio-net
    driver: bridge
