name: Continuous Integration

on:
  push:
    branches: 
      - "development"
      - "feat/**"
      - "fix/**"
      - "docs/**"
      - "style/**"
      - "refactor/**"
      - "test/**"
      - "chore/**"
  pull_request:
    branches: 
      - "development"
      - "main"

jobs:
  build-and-test:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0

    - uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Build
      run: |
        pnpm build
        cd build
        zip -r ../build.zip .
        cd ..

    - name: Set Version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/pull/* ]]; then
          PR_NUMBER=$(echo $GITHUB_REF | cut -d / -f 3)
          VERSION="pr-${PR_NUMBER}-$(git rev-parse --short HEAD)"
        else
          VERSION=$(git rev-parse --short HEAD)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # Upload to Nexus except for PRs to main
    - name: Upload to Nexus
      if: github.base_ref != 'main'
      env:
        NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        curl -u "${{ secrets.NEXUS_USERNAME }}:$NEXUS_PASS" \
          --upload-file build.zip \
          "https://pkg.rumblersoppa.com.br/repository/raw-hosted/rumbler-portfolio/${{ steps.version.outputs.version }}/build.zip"
