name: Continuous Integration

on:
  push:
    branches: 
      - "feat/**"
      - "fix/**"
      - "docs/**"
      - "style/**"
      - "refactor/**"
      - "test/**"
      - "chore/**"
    tags:
      - 'v*'  
  pull_request:
    branches: 
      - "development"
      - "main"
  pull_request_target:
    types: [closed]
    branches:
      - "development"
      - "main"

jobs:
  build-and-test:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.version.outputs.version }}
      environment: ${{ steps.version.outputs.environment }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0

    - uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Build
      run: pnpm build

    - name: Set Version and Environment
      id: version
      run: |
        if [[ $GITHUB_EVENT_NAME == 'pull_request_target' && ${{ github.event.pull_request.merged }} == true ]]; then
          # PR foi merged
          if [[ $GITHUB_BASE_REF == 'development' ]]; then
            # PR merged na development
            VERSION=$(git rev-parse --short HEAD)
            ENVIRONMENT="development"
          elif [[ $GITHUB_BASE_REF == 'main' ]]; then
            # PR merged na main -> release
            VERSION="v$(git rev-parse --short HEAD)"
            ENVIRONMENT="release"
          fi
        elif [[ $GITHUB_EVENT_NAME == 'push' && $GITHUB_REF == refs/tags/* ]]; then
          # Push de tag -> production
          VERSION=${GITHUB_REF#refs/tags/}
          ENVIRONMENT="production"
        else
          # Outros casos - não fazemos upload
          VERSION=$(git rev-parse --short HEAD)
          ENVIRONMENT="none"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

    # Upload to Nexus apenas nos casos específicos
    - name: Create and Upload Artifact
      if: |
        (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && github.base_ref == 'development') ||
        (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && github.base_ref == 'main') ||
        (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
      env:
        NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_URL: ${{ secrets.NEXUS_URL }}
        NEXUS_REPO: ${{ secrets.NEXUS_REPOSITORY }}
      run: |
        # Create zip
        cd build
        zip -r ../build.zip .
        cd ..
        
        # Upload to Nexus
        curl -u "${{ secrets.NEXUS_USERNAME }}:$NEXUS_PASS" \
          --upload-file build.zip \
          "${NEXUS_URL}/repository/${NEXUS_REPO}/${{ github.event.repository.name }}/${{ steps.version.outputs.environment }}/${{ steps.version.outputs.version }}.zip"
