name: Continuous Integration

on:
  push:
    branches: ["development", "main"]  # Main needs push trigger for RC tags
    tags:
      - 'v*'
  pull_request:
    branches: ["main", "development"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0

    - uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Build
      run: |
        pnpm build
        cd build
        zip -r ../build.zip .
        cd ..

    - name: Set Version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # For production tags (v*)
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/main ]]; then
          # For main branch (via PR merge), create RC tag with commit hash
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION="${LAST_TAG%-*}-rc.${COMMIT_HASH}"
          # Create and push RC tag
          git tag $VERSION
          git push origin $VERSION
        else
          # For development and other branches
          VERSION=$(git rev-parse --short HEAD)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # Upload to Nexus except for PRs
    - name: Upload to Nexus
      if: github.event_name != 'pull_request'
      env:
        NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        curl -u "${{ secrets.NEXUS_USERNAME }}:$NEXUS_PASS" \
          --upload-file build.zip \
          "https://pkg.rumblersoppa.com.br/repository/raw-hosted/rumbler-portfolio/${{ steps.version.outputs.version }}/build.zip"

  # Deploy to development only on push to development branch
  call-development-deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    uses: ./.github/workflows/development.yml
    with:
      version: ${{ needs.build-and-test.outputs.version }}
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  # Deploy to release only after PR merge to main
  call-release-deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.build-and-test.outputs.version }}
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  # Deploy to production only on version tags
  call-production-deploy:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/production.yml
    with:
      version: ${{ needs.build-and-test.outputs.version }}
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}
