name: Continuous Integration

on:
  push:
    branches: [ "main", "development" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0

    - uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Build
      run: |
        pnpm build
        cd build
        zip -r ../build.zip .
        cd ..

    - name: Set Version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=$(git rev-parse --short HEAD)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # Upload para o Nexus apenas se não for a branch main
    - name: Upload to Nexus
      if: github.ref != 'refs/heads/main'
      env:
        NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        curl -u "${{ secrets.NEXUS_USERNAME }}:$NEXUS_PASS" \
          --upload-file build.zip \
          "https://pkg.rumblersoppa.com.br/repository/raw-hosted/rumbler-portfolio/${{ steps.version.outputs.version }}/build.zip"

  # Deploy para desenvolvimento apenas se for branch development ou PR para development
  call-development-deploy:
    needs: build-and-test
    if: (github.ref == 'refs/heads/development' || github.event_name == 'pull_request') && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/development.yml
    with:
      version: ${{ needs.build-and-test.outputs.version }}
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}
