name: Continuous Integration
permissions:
  packages: write
  contents: read
  actions: read
  checks: write  
  deployments: write
  security-events: write

on:
  push:
    branches: 
      - "development"
      - "main"
      - "feat/*"
      - "fix/*"
      - "hotfix/*"
      - "bugfix/*"
      - "support/*"
    tags:
      - 'v*-rc.*'
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  build-and-upload:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Set version and environment
        id: version
        if: |
          github.event_name == 'push' && (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/fix/') || startsWith(github.ref, 'refs/heads/hotfix/') || startsWith(github.ref, 'refs/heads/release/'))
        run: |
          case "${{ github.ref }}" in
            refs/heads/development) VERSION="$(git rev-parse --short HEAD)"; ENVIRONMENT="development" ;;
            refs/heads/main)       VERSION="rc-$(git rev-parse --short HEAD)"; ENVIRONMENT="release" ;;
            refs/tags/v[0-9]*.[0-9]*.[0-9]*) VERSION="${{ github.ref_name }}"; ENVIRONMENT="production" ;;
            refs/heads/feat/*)     VERSION="feat-$(git rev-parse --short HEAD)"; ENVIRONMENT="development" ;;
            refs/heads/fix/*)      VERSION="fix-$(git rev-parse --short HEAD)"; ENVIRONMENT="development" ;;
            refs/heads/hotfix/*)   VERSION="hotfix-$(git rev-parse --short HEAD)"; ENVIRONMENT="release" ;;
            refs/heads/release/*)  VERSION="release-$(git rev-parse --short HEAD)"; ENVIRONMENT="release" ;;
            *)                     VERSION="dev-$(git rev-parse --short HEAD)"; ENVIRONMENT="development" ;;
          esac

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 9.15.9

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 24.8.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          NODE_ENV: ${{ steps.version.outputs.environment }}
          REACT_APP_EMAIL_URL: ${{ secrets.REACT_APP_EMAIL_URL }}
          REACT_APP_GITHUB_URL: ${{ secrets.REACT_APP_GITHUB_URL }}
          REACT_APP_LINKEDIN_URL: ${{ secrets.REACT_APP_LINKEDIN_URL }}
          REACT_APP_WHATSAPP_URL: ${{ secrets.REACT_APP_WHATSAPP_URL }}
        run: |
          pnpm run build

      - name: Run tests
        run: pnpm test

      - uses: sonarsource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln'
          output: 'trivy-dependency-report.sarif'

      - name: Run Trivy to Scan for Misconfigurations
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          exit-code: '0'
          ignore-unfixed: true
          skip-dirs: 'node_modules'
          scanners: 'misconfig'
          output: 'trivy-misconfig-report.sarif'

      - name: Upload Trivy Dependency Report to GitHub
        uses: github/codeql-action/upload-sarif@d378195403bf7cd9c9b55e4713ede0962aa58b83
        with:
          sarif_file: trivy-dependency-report.sarif
          category: trivy-dependency-scan

      - name: Upload Trivy Misconfigurations Report to GitHub
        uses: github/codeql-action/upload-sarif@d378195403bf7cd9c9b55e4713ede0962aa58b83
        with:
          sarif_file: trivy-misconfig-report.sarif
          category: trivy-misconfig-scan

      - name: Build Docker image
        if: |
          github.event_name == 'push' && 
          (steps.version.outputs.environment == 'development' || 
           steps.version.outputs.environment == 'release' || 
           steps.version.outputs.environment == 'production')
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
        run: |
          docker build -t $DOCKER_REGISTRY_URL/${REPOSITORY_NAME}:${{ steps.version.outputs.version }} .

      - name: Push Docker image to Harbor
        if: |
          github.event_name == 'push' && 
          (steps.version.outputs.environment == 'development' || 
           steps.version.outputs.environment == 'release' || 
           steps.version.outputs.environment == 'production')
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
        run: |
          docker push $DOCKER_REGISTRY_URL/${REPOSITORY_NAME}:${{ steps.version.outputs.version }}
