name: Production CD

on:
  push:
    tags:
      - 'v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'

permissions:
  packages: write
  contents: read
  actions: read
  checks: write
  deployments: write

jobs:
  deploy-production:
    name: Deploy to Production
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    environment: production
    env:
      NODE_ENV: production
      PORT: 3000
      DOCKER_CPU_LIMIT: 1
      DOCKER_MEMORY_LIMIT: 512M
      DOCKER_CPU_RESERVE: 0.75
      DOCKER_MEMORY_RESERVE: 384M
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version from tag
        if: github.event.inputs.version == ''
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}  # Remove o prefixo 'refs/tags/v'
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Download build from Nexus
        env:
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_REPO: ${{ secrets.NEXUS_REPOSITORY }}
        run: |
          mkdir -p build
          TAG=${GITHUB_REF#refs/tags/}
          curl -u "${{ secrets.NEXUS_USERNAME }}:$NEXUS_PASS" \
            -o build.zip \
            "${NEXUS_URL}/repository/${NEXUS_REPO}/${{ github.event.repository.name }}/production/${TAG}.zip"
          unzip build.zip -d build/

      - name: Build and push Docker image
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          # Login no Docker Registry
          echo "$NEXUS_PASS" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin
          
          VERSION=${{ github.event.inputs.version || steps.get_version.outputs.version }}
          docker build -t ${REGISTRY_URL}/rumbler-portfolio:${VERSION} .
          docker push ${REGISTRY_URL}/rumbler-portfolio:${VERSION}
          
          # Tag as latest
          docker tag ${REGISTRY_URL}/rumbler-portfolio:${VERSION} ${REGISTRY_URL}/rumbler-portfolio:latest
          docker push ${REGISTRY_URL}/rumbler-portfolio:latest

      - name: Deploy to Production
        env:
          PROD_IMAGE_TAG: ${{ github.event.inputs.version }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
          PROD_PORT: 3000
          PROD_CPU_LIMIT: 1.0
          PROD_MEMORY_LIMIT: 512M
          PROD_CPU_RESERVE: 0.75
          PROD_MEMORY_RESERVE: 384M
        run: |
          # Login no Docker Registry
          echo "$NEXUS_PASS" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin
          
          # Pull new image first
          docker compose pull portfolio-production
          
          # Rolling update - zero downtime
          docker compose up -d --no-deps --build --force-recreate --remove-orphans portfolio-production
