name: Production CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: read
  actions: read
  checks: write
  deployments: write

jobs:
  deploy-production:
    name: Deploy to Production
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    environment: production
    env:
      NODE_ENV: production
      PORT: 3000
      DOCKER_CPU_LIMIT: 1
      DOCKER_MEMORY_LIMIT: 512M
      DOCKER_CPU_RESERVE: 0.75
      DOCKER_MEMORY_RESERVE: 384M
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version from tag
        if: github.event.inputs.version == ''
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}  # Remove o prefixo 'refs/tags/v'
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Download build from Nexus
        env:
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_REPO: ${{ secrets.NEXUS_REPOSITORY }}
        run: |
          mkdir -p build
          TAG=${GITHUB_REF#refs/tags/}
          curl -u "${{ secrets.NEXUS_USERNAME }}:$NEXUS_PASS" \
            -o build.zip \
            "${NEXUS_URL}/repository/${NEXUS_REPO}/${{ github.event.repository.name }}/production/${TAG}.zip"
          unzip build.zip -d build/

      - name: Build and push Docker image
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        run: |
          VERSION=${{ github.event.inputs.version || steps.get_version.outputs.version }}
          docker build -t ${REGISTRY_URL}/${{ github.event.repository.name }}:${VERSION} .
          docker push ${REGISTRY_URL}/${{ github.event.repository.name }}:${VERSION}
          
          # Tag as latest
          docker tag ${REGISTRY_URL}/${{ github.event.repository.name }}:${VERSION} ${REGISTRY_URL}/${{ github.event.repository.name }}:latest
          docker push ${REGISTRY_URL}/${{ github.event.repository.name }}:latest

      - name: Deploy to Production
        env:
          IMAGE_TAG: ${{ github.event.inputs.version || steps.get_version.outputs.version }}
        run: |
          # Pull new image first
          docker compose -f docker-compose.yml -f docker-compose.production.yml pull
          
          # Rolling update - zero downtime
          docker compose -f docker-compose.yml -f docker-compose.production.yml up -d --no-deps --build --force-recreate --remove-orphans
