name: Continuous Deployment to Release Environment

on:
  push:
    branches:
      - "main"

permissions:
  packages: write
  contents: read
  actions: read
  checks: write
  deployments: write

jobs:
  deploy-release:
    name: Deploy to Release
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: release
    env:
      NODE_ENV: release
      PORT: 3002
      PRODUCTION_DOMAIN: ${{ secrets.RELEASE_DOMAIN }}
      DOCKER_CPU_LIMIT: 0.75
      DOCKER_MEMORY_LIMIT: 384M
      DOCKER_CPU_RESERVE: 0.5
      DOCKER_MEMORY_RESERVE: 256M
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version and environment
        id: version
        run: |
          # Pega o SHA do commit
          COMMIT_SHA=${{ github.sha }}
          # Cria uma tag temporária no formato rc-{7 primeiros caracteres do SHA}
          VERSION="rc-${COMMIT_SHA:0:7}"
          ENVIRONMENT="release"

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT

      - name: Download build from Nexus
        env:
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_REPO: ${{ secrets.NEXUS_REPOSITORY }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          NEXUS_ENV: ${{ steps.version.outputs.environment }}
          NEXUS_VERSION: ${{ steps.version.outputs.version }}
        run: |
          mkdir -p build
          curl -u "$NEXUS_USERNAME:$NEXUS_PASS" \
            -o build.zip \
            "${NEXUS_URL}/repository/${NEXUS_REPO}/${REPOSITORY_NAME}/${NEXUS_ENV}/${NEXUS_VERSION}.zip"
            
            if [ ! -f build.zip ]; then
              echo "Error: Build file not downloaded"
              exit 1
            fi

          unzip build.zip -d build/

      - name: Build and push Docker image
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          NEXUS_ENV: ${{ steps.version.outputs.environment }}
          NEXUS_VERSION: ${{ steps.version.outputs.version }}
        run: |
          # Login no Docker Registry
          echo "$NEXUS_PASS" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin
          
          docker build -t ${REGISTRY_URL}/${REPOSITORY_NAME}:${NEXUS_VERSION} .
          docker push ${REGISTRY_URL}/rumbler-portfolio:${NEXUS_VERSION}
          
          # Tag as release
          docker tag ${REGISTRY_URL}/${REPOSITORY_NAME}:${NEXUS_VERSION} ${REGISTRY_URL}/${REPOSITORY_NAME}:release
          docker push ${REGISTRY_URL}/${REPOSITORY_NAME}:release

      - name: Deploy to Release
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          RELEASE_IMAGE_TAG: ${{ steps.version.outputs.version }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
          RELEASE_PORT: 3002
          RELEASE_CPU_LIMIT: 0.75
          RELEASE_MEMORY_LIMIT: 384M
          RELEASE_CPU_RESERVE: 0.5
          RELEASE_MEMORY_RESERVE: 256M
          PRODUCTION_DOMAIN: ${{ secrets.RELEASE_DOMAIN }}
        run: |
          echo "Logging into Docker Registry..."
          echo "$NEXUS_PASS" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin
          
          echo "Pulling the latest release image..."
          docker compose pull portfolio-release
          
          echo "Deploying the updated release container..."
          docker compose up -d \
            --no-deps \
            --remove-orphans \
            portfolio-release

          echo "Deployment to the release environment completed successfully."
